//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_CustomerDetails_Areas", "Areas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.Area), "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.CustomerDetail), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_BillingHistory_CustomerDetails", "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.CustomerDetail), "CustomerDues", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KanakTiffins.CustomerDue), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_CustomerDetails_LunchOrDinner", "LunchOrDinner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.LunchOrDinner), "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.CustomerDetail), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_CustomerDetails_MealPlans", "MealPlans", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.MealPlan), "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.CustomerDetail), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.CustomerDetail), "CustomerPaymentHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.CustomerPaymentHistory), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_CustomerDetails", "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.CustomerDetail), "ExtraCharges", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.ExtraCharge), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_MonthlyBills_CustomerDetails", "CustomerDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.CustomerDetail), "MonthlyBills", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.MonthlyBill), true)]
[assembly: EdmRelationshipAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_Months", "Months", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KanakTiffins.Month), "ExtraCharges", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KanakTiffins.ExtraCharge), true)]

#endregion

namespace KanakTiffins
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KanakTiffinsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KanakTiffinsEntities object using the connection string found in the 'KanakTiffinsEntities' section of the application configuration file.
        /// </summary>
        public KanakTiffinsEntities() : base("name=KanakTiffinsEntities", "KanakTiffinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KanakTiffinsEntities object.
        /// </summary>
        public KanakTiffinsEntities(string connectionString) : base(connectionString, "KanakTiffinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KanakTiffinsEntities object.
        /// </summary>
        public KanakTiffinsEntities(EntityConnection connection) : base(connection, "KanakTiffinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Area> Areas
        {
            get
            {
                if ((_Areas == null))
                {
                    _Areas = base.CreateObjectSet<Area>("Areas");
                }
                return _Areas;
            }
        }
        private ObjectSet<Area> _Areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerDetail> CustomerDetails
        {
            get
            {
                if ((_CustomerDetails == null))
                {
                    _CustomerDetails = base.CreateObjectSet<CustomerDetail>("CustomerDetails");
                }
                return _CustomerDetails;
            }
        }
        private ObjectSet<CustomerDetail> _CustomerDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerDue> CustomerDues
        {
            get
            {
                if ((_CustomerDues == null))
                {
                    _CustomerDues = base.CreateObjectSet<CustomerDue>("CustomerDues");
                }
                return _CustomerDues;
            }
        }
        private ObjectSet<CustomerDue> _CustomerDues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerPaymentHistory> CustomerPaymentHistories
        {
            get
            {
                if ((_CustomerPaymentHistories == null))
                {
                    _CustomerPaymentHistories = base.CreateObjectSet<CustomerPaymentHistory>("CustomerPaymentHistories");
                }
                return _CustomerPaymentHistories;
            }
        }
        private ObjectSet<CustomerPaymentHistory> _CustomerPaymentHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExtraCharge> ExtraCharges
        {
            get
            {
                if ((_ExtraCharges == null))
                {
                    _ExtraCharges = base.CreateObjectSet<ExtraCharge>("ExtraCharges");
                }
                return _ExtraCharges;
            }
        }
        private ObjectSet<ExtraCharge> _ExtraCharges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LunchOrDinner> LunchOrDinners
        {
            get
            {
                if ((_LunchOrDinners == null))
                {
                    _LunchOrDinners = base.CreateObjectSet<LunchOrDinner>("LunchOrDinners");
                }
                return _LunchOrDinners;
            }
        }
        private ObjectSet<LunchOrDinner> _LunchOrDinners;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MealPlan> MealPlans
        {
            get
            {
                if ((_MealPlans == null))
                {
                    _MealPlans = base.CreateObjectSet<MealPlan>("MealPlans");
                }
                return _MealPlans;
            }
        }
        private ObjectSet<MealPlan> _MealPlans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MonthlyBill> MonthlyBills
        {
            get
            {
                if ((_MonthlyBills == null))
                {
                    _MonthlyBills = base.CreateObjectSet<MonthlyBill>("MonthlyBills");
                }
                return _MonthlyBills;
            }
        }
        private ObjectSet<MonthlyBill> _MonthlyBills;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Month> Months
        {
            get
            {
                if ((_Months == null))
                {
                    _Months = base.CreateObjectSet<Month>("Months");
                }
                return _Months;
            }
        }
        private ObjectSet<Month> _Months;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreas(Area area)
        {
            base.AddObject("Areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerDetails(CustomerDetail customerDetail)
        {
            base.AddObject("CustomerDetails", customerDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerDues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerDues(CustomerDue customerDue)
        {
            base.AddObject("CustomerDues", customerDue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerPaymentHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerPaymentHistories(CustomerPaymentHistory customerPaymentHistory)
        {
            base.AddObject("CustomerPaymentHistories", customerPaymentHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExtraCharges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExtraCharges(ExtraCharge extraCharge)
        {
            base.AddObject("ExtraCharges", extraCharge);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LunchOrDinners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLunchOrDinners(LunchOrDinner lunchOrDinner)
        {
            base.AddObject("LunchOrDinners", lunchOrDinner);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MealPlans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMealPlans(MealPlan mealPlan)
        {
            base.AddObject("MealPlans", mealPlan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MonthlyBills EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonthlyBills(MonthlyBill monthlyBill)
        {
            base.AddObject("MonthlyBills", monthlyBill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Months EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonths(Month month)
        {
            base.AddObject("Months", month);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Area object.
        /// </summary>
        /// <param name="areaId">Initial value of the AreaId property.</param>
        /// <param name="areaName">Initial value of the AreaName property.</param>
        public static Area CreateArea(global::System.Int32 areaId, global::System.String areaName)
        {
            Area area = new Area();
            area.AreaId = areaId;
            area.AreaName = areaName;
            return area;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AreaId
        {
            get
            {
                return _AreaId;
            }
            set
            {
                if (_AreaId != value)
                {
                    OnAreaIdChanging(value);
                    ReportPropertyChanging("AreaId");
                    _AreaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AreaId");
                    OnAreaIdChanged();
                }
            }
        }
        private global::System.Int32 _AreaId;
        partial void OnAreaIdChanging(global::System.Int32 value);
        partial void OnAreaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AreaName
        {
            get
            {
                return _AreaName;
            }
            set
            {
                OnAreaNameChanging(value);
                ReportPropertyChanging("AreaName");
                _AreaName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AreaName");
                OnAreaNameChanged();
            }
        }
        private global::System.String _AreaName;
        partial void OnAreaNameChanging(global::System.String value);
        partial void OnAreaNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_Areas", "CustomerDetails")]
        public EntityCollection<CustomerDetail> CustomerDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_Areas", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_Areas", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="CustomerDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerDetail object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="areaId">Initial value of the AreaId property.</param>
        /// <param name="mealPlanId">Initial value of the MealPlanId property.</param>
        /// <param name="lunchOrDinnerId">Initial value of the LunchOrDinnerId property.</param>
        /// <param name="defaultDabbawalaCharges">Initial value of the DefaultDabbawalaCharges property.</param>
        /// <param name="initialBalance">Initial value of the InitialBalance property.</param>
        public static CustomerDetail CreateCustomerDetail(global::System.Int32 customerId, global::System.String firstName, global::System.String address, global::System.String phoneNumber, global::System.Int32 areaId, global::System.Int32 mealPlanId, global::System.Int32 lunchOrDinnerId, global::System.Int32 defaultDabbawalaCharges, global::System.Int32 initialBalance)
        {
            CustomerDetail customerDetail = new CustomerDetail();
            customerDetail.CustomerId = customerId;
            customerDetail.FirstName = firstName;
            customerDetail.Address = address;
            customerDetail.PhoneNumber = phoneNumber;
            customerDetail.AreaId = areaId;
            customerDetail.MealPlanId = mealPlanId;
            customerDetail.LunchOrDinnerId = lunchOrDinnerId;
            customerDetail.DefaultDabbawalaCharges = defaultDabbawalaCharges;
            customerDetail.InitialBalance = initialBalance;
            return customerDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepositAmount
        {
            get
            {
                return _DepositAmount;
            }
            set
            {
                OnDepositAmountChanging(value);
                ReportPropertyChanging("DepositAmount");
                _DepositAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepositAmount");
                OnDepositAmountChanged();
            }
        }
        private Nullable<global::System.Int32> _DepositAmount;
        partial void OnDepositAmountChanging(Nullable<global::System.Int32> value);
        partial void OnDepositAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AreaId
        {
            get
            {
                return _AreaId;
            }
            set
            {
                OnAreaIdChanging(value);
                ReportPropertyChanging("AreaId");
                _AreaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AreaId");
                OnAreaIdChanged();
            }
        }
        private global::System.Int32 _AreaId;
        partial void OnAreaIdChanging(global::System.Int32 value);
        partial void OnAreaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealPlanId
        {
            get
            {
                return _MealPlanId;
            }
            set
            {
                OnMealPlanIdChanging(value);
                ReportPropertyChanging("MealPlanId");
                _MealPlanId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MealPlanId");
                OnMealPlanIdChanged();
            }
        }
        private global::System.Int32 _MealPlanId;
        partial void OnMealPlanIdChanging(global::System.Int32 value);
        partial void OnMealPlanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LunchOrDinnerId
        {
            get
            {
                return _LunchOrDinnerId;
            }
            set
            {
                OnLunchOrDinnerIdChanging(value);
                ReportPropertyChanging("LunchOrDinnerId");
                _LunchOrDinnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LunchOrDinnerId");
                OnLunchOrDinnerIdChanged();
            }
        }
        private global::System.Int32 _LunchOrDinnerId;
        partial void OnLunchOrDinnerIdChanging(global::System.Int32 value);
        partial void OnLunchOrDinnerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DefaultDabbawalaCharges
        {
            get
            {
                return _DefaultDabbawalaCharges;
            }
            set
            {
                OnDefaultDabbawalaChargesChanging(value);
                ReportPropertyChanging("DefaultDabbawalaCharges");
                _DefaultDabbawalaCharges = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultDabbawalaCharges");
                OnDefaultDabbawalaChargesChanged();
            }
        }
        private global::System.Int32 _DefaultDabbawalaCharges;
        partial void OnDefaultDabbawalaChargesChanging(global::System.Int32 value);
        partial void OnDefaultDabbawalaChargesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InitialBalance
        {
            get
            {
                return _InitialBalance;
            }
            set
            {
                OnInitialBalanceChanging(value);
                ReportPropertyChanging("InitialBalance");
                _InitialBalance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InitialBalance");
                OnInitialBalanceChanged();
            }
        }
        private global::System.Int32 _InitialBalance;
        partial void OnInitialBalanceChanging(global::System.Int32 value);
        partial void OnInitialBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String isDeleted
        {
            get
            {
                return _isDeleted;
            }
            set
            {
                OnisDeletedChanging(value);
                ReportPropertyChanging("isDeleted");
                _isDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("isDeleted");
                OnisDeletedChanged();
            }
        }
        private global::System.String _isDeleted;
        partial void OnisDeletedChanging(global::System.String value);
        partial void OnisDeletedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_Areas", "Areas")]
        public Area Area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("KanakTiffinsModel.FK_CustomerDetails_Areas", "Areas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("KanakTiffinsModel.FK_CustomerDetails_Areas", "Areas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Area> AreaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("KanakTiffinsModel.FK_CustomerDetails_Areas", "Areas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Area>("KanakTiffinsModel.FK_CustomerDetails_Areas", "Areas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_BillingHistory_CustomerDetails", "CustomerDues")]
        public CustomerDue CustomerDue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDue>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDues").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDue>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDues").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerDue> CustomerDueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDue>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDues");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerDue>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDues", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_LunchOrDinner", "LunchOrDinner")]
        public LunchOrDinner LunchOrDinner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LunchOrDinner>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "LunchOrDinner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LunchOrDinner>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "LunchOrDinner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LunchOrDinner> LunchOrDinnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LunchOrDinner>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "LunchOrDinner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LunchOrDinner>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "LunchOrDinner", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_MealPlans", "MealPlans")]
        public MealPlan MealPlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MealPlan>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "MealPlans").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MealPlan>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "MealPlans").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MealPlan> MealPlanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MealPlan>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "MealPlans");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MealPlan>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "MealPlans", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerPaymentHistory_CustomerDetails", "CustomerPaymentHistory")]
        public EntityCollection<CustomerPaymentHistory> CustomerPaymentHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerPaymentHistory>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerPaymentHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerPaymentHistory>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerPaymentHistory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_CustomerDetails", "ExtraCharges")]
        public EntityCollection<ExtraCharge> ExtraCharges
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExtraCharge>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "ExtraCharges");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExtraCharge>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "ExtraCharges", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_MonthlyBills_CustomerDetails", "MonthlyBills")]
        public EntityCollection<MonthlyBill> MonthlyBills
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MonthlyBill>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "MonthlyBills");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MonthlyBill>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "MonthlyBills", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="CustomerDue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerDue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerDue object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="dueAmount">Initial value of the DueAmount property.</param>
        /// <param name="carryforwardAmount">Initial value of the CarryforwardAmount property.</param>
        public static CustomerDue CreateCustomerDue(global::System.Int32 customerId, global::System.Int32 dueAmount, global::System.Int32 carryforwardAmount)
        {
            CustomerDue customerDue = new CustomerDue();
            customerDue.CustomerId = customerId;
            customerDue.DueAmount = dueAmount;
            customerDue.CarryforwardAmount = carryforwardAmount;
            return customerDue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DueAmount
        {
            get
            {
                return _DueAmount;
            }
            set
            {
                OnDueAmountChanging(value);
                ReportPropertyChanging("DueAmount");
                _DueAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueAmount");
                OnDueAmountChanged();
            }
        }
        private global::System.Int32 _DueAmount;
        partial void OnDueAmountChanging(global::System.Int32 value);
        partial void OnDueAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarryforwardAmount
        {
            get
            {
                return _CarryforwardAmount;
            }
            set
            {
                OnCarryforwardAmountChanging(value);
                ReportPropertyChanging("CarryforwardAmount");
                _CarryforwardAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarryforwardAmount");
                OnCarryforwardAmountChanged();
            }
        }
        private global::System.Int32 _CarryforwardAmount;
        partial void OnCarryforwardAmountChanging(global::System.Int32 value);
        partial void OnCarryforwardAmountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_BillingHistory_CustomerDetails", "CustomerDetails")]
        public CustomerDetail CustomerDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerDetail> CustomerDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_BillingHistory_CustomerDetails", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="CustomerPaymentHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerPaymentHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerPaymentHistory object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="paidAmount">Initial value of the PaidAmount property.</param>
        /// <param name="paidOn">Initial value of the PaidOn property.</param>
        public static CustomerPaymentHistory CreateCustomerPaymentHistory(global::System.Int32 customerId, global::System.Int32 paidAmount, global::System.DateTime paidOn)
        {
            CustomerPaymentHistory customerPaymentHistory = new CustomerPaymentHistory();
            customerPaymentHistory.CustomerId = customerId;
            customerPaymentHistory.PaidAmount = paidAmount;
            customerPaymentHistory.PaidOn = paidOn;
            return customerPaymentHistory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaidAmount
        {
            get
            {
                return _PaidAmount;
            }
            set
            {
                OnPaidAmountChanging(value);
                ReportPropertyChanging("PaidAmount");
                _PaidAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaidAmount");
                OnPaidAmountChanged();
            }
        }
        private global::System.Int32 _PaidAmount;
        partial void OnPaidAmountChanging(global::System.Int32 value);
        partial void OnPaidAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PaidOn
        {
            get
            {
                return _PaidOn;
            }
            set
            {
                if (_PaidOn != value)
                {
                    OnPaidOnChanging(value);
                    ReportPropertyChanging("PaidOn");
                    _PaidOn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaidOn");
                    OnPaidOnChanged();
                }
            }
        }
        private global::System.DateTime _PaidOn;
        partial void OnPaidOnChanging(global::System.DateTime value);
        partial void OnPaidOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaymentMethod
        {
            get
            {
                return _PaymentMethod;
            }
            set
            {
                OnPaymentMethodChanging(value);
                ReportPropertyChanging("PaymentMethod");
                _PaymentMethod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaymentMethod");
                OnPaymentMethodChanged();
            }
        }
        private global::System.String _PaymentMethod;
        partial void OnPaymentMethodChanging(global::System.String value);
        partial void OnPaymentMethodChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails")]
        public CustomerDetail CustomerDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerDetail> CustomerDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_CustomerPaymentHistory_CustomerDetails", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="ExtraCharge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExtraCharge : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExtraCharge object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="monthId">Initial value of the MonthId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="dabbawalaCharges">Initial value of the DabbawalaCharges property.</param>
        /// <param name="deliveryCharges">Initial value of the DeliveryCharges property.</param>
        public static ExtraCharge CreateExtraCharge(global::System.Int32 customerId, global::System.Int32 monthId, global::System.Int32 year, global::System.Int32 dabbawalaCharges, global::System.Int32 deliveryCharges)
        {
            ExtraCharge extraCharge = new ExtraCharge();
            extraCharge.CustomerId = customerId;
            extraCharge.MonthId = monthId;
            extraCharge.Year = year;
            extraCharge.DabbawalaCharges = dabbawalaCharges;
            extraCharge.DeliveryCharges = deliveryCharges;
            return extraCharge;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MonthId
        {
            get
            {
                return _MonthId;
            }
            set
            {
                if (_MonthId != value)
                {
                    OnMonthIdChanging(value);
                    ReportPropertyChanging("MonthId");
                    _MonthId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MonthId");
                    OnMonthIdChanged();
                }
            }
        }
        private global::System.Int32 _MonthId;
        partial void OnMonthIdChanging(global::System.Int32 value);
        partial void OnMonthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    OnYearChanging(value);
                    ReportPropertyChanging("Year");
                    _Year = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Year");
                    OnYearChanged();
                }
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DabbawalaCharges
        {
            get
            {
                return _DabbawalaCharges;
            }
            set
            {
                OnDabbawalaChargesChanging(value);
                ReportPropertyChanging("DabbawalaCharges");
                _DabbawalaCharges = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DabbawalaCharges");
                OnDabbawalaChargesChanged();
            }
        }
        private global::System.Int32 _DabbawalaCharges;
        partial void OnDabbawalaChargesChanging(global::System.Int32 value);
        partial void OnDabbawalaChargesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeliveryCharges
        {
            get
            {
                return _DeliveryCharges;
            }
            set
            {
                OnDeliveryChargesChanging(value);
                ReportPropertyChanging("DeliveryCharges");
                _DeliveryCharges = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryCharges");
                OnDeliveryChargesChanged();
            }
        }
        private global::System.Int32 _DeliveryCharges;
        partial void OnDeliveryChargesChanging(global::System.Int32 value);
        partial void OnDeliveryChargesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_CustomerDetails", "CustomerDetails")]
        public CustomerDetail CustomerDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "CustomerDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "CustomerDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerDetail> CustomerDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_DabbawalaCharges_CustomerDetails", "CustomerDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_Months", "Months")]
        public Month Month
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Month>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "Months").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Month>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "Months").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Month> MonthReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Month>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "Months");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Month>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "Months", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="LunchOrDinner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LunchOrDinner : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LunchOrDinner object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static LunchOrDinner CreateLunchOrDinner(global::System.Int32 id, global::System.String name)
        {
            LunchOrDinner lunchOrDinner = new LunchOrDinner();
            lunchOrDinner.Id = id;
            lunchOrDinner.Name = name;
            return lunchOrDinner;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_LunchOrDinner", "CustomerDetails")]
        public EntityCollection<CustomerDetail> CustomerDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_LunchOrDinner", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="MealPlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MealPlan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MealPlan object.
        /// </summary>
        /// <param name="mealPlanId">Initial value of the MealPlanId property.</param>
        /// <param name="mealAmount">Initial value of the MealAmount property.</param>
        public static MealPlan CreateMealPlan(global::System.Int32 mealPlanId, global::System.Int32 mealAmount)
        {
            MealPlan mealPlan = new MealPlan();
            mealPlan.MealPlanId = mealPlanId;
            mealPlan.MealAmount = mealAmount;
            return mealPlan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealPlanId
        {
            get
            {
                return _MealPlanId;
            }
            set
            {
                if (_MealPlanId != value)
                {
                    OnMealPlanIdChanging(value);
                    ReportPropertyChanging("MealPlanId");
                    _MealPlanId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MealPlanId");
                    OnMealPlanIdChanged();
                }
            }
        }
        private global::System.Int32 _MealPlanId;
        partial void OnMealPlanIdChanging(global::System.Int32 value);
        partial void OnMealPlanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealAmount
        {
            get
            {
                return _MealAmount;
            }
            set
            {
                OnMealAmountChanging(value);
                ReportPropertyChanging("MealAmount");
                _MealAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MealAmount");
                OnMealAmountChanged();
            }
        }
        private global::System.Int32 _MealAmount;
        partial void OnMealAmountChanging(global::System.Int32 value);
        partial void OnMealAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MealDescription
        {
            get
            {
                return _MealDescription;
            }
            set
            {
                OnMealDescriptionChanging(value);
                ReportPropertyChanging("MealDescription");
                _MealDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MealDescription");
                OnMealDescriptionChanged();
            }
        }
        private global::System.String _MealDescription;
        partial void OnMealDescriptionChanging(global::System.String value);
        partial void OnMealDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_CustomerDetails_MealPlans", "CustomerDetails")]
        public EntityCollection<CustomerDetail> CustomerDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerDetail>("KanakTiffinsModel.FK_CustomerDetails_MealPlans", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="Month")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Month : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Month object.
        /// </summary>
        /// <param name="monthId">Initial value of the MonthId property.</param>
        /// <param name="monthName">Initial value of the MonthName property.</param>
        public static Month CreateMonth(global::System.Int32 monthId, global::System.String monthName)
        {
            Month month = new Month();
            month.MonthId = monthId;
            month.MonthName = monthName;
            return month;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MonthId
        {
            get
            {
                return _MonthId;
            }
            set
            {
                if (_MonthId != value)
                {
                    OnMonthIdChanging(value);
                    ReportPropertyChanging("MonthId");
                    _MonthId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MonthId");
                    OnMonthIdChanged();
                }
            }
        }
        private global::System.Int32 _MonthId;
        partial void OnMonthIdChanging(global::System.Int32 value);
        partial void OnMonthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MonthName
        {
            get
            {
                return _MonthName;
            }
            set
            {
                OnMonthNameChanging(value);
                ReportPropertyChanging("MonthName");
                _MonthName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MonthName");
                OnMonthNameChanged();
            }
        }
        private global::System.String _MonthName;
        partial void OnMonthNameChanging(global::System.String value);
        partial void OnMonthNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_DabbawalaCharges_Months", "ExtraCharges")]
        public EntityCollection<ExtraCharge> ExtraCharges
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExtraCharge>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "ExtraCharges");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExtraCharge>("KanakTiffinsModel.FK_DabbawalaCharges_Months", "ExtraCharges", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KanakTiffinsModel", Name="MonthlyBill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MonthlyBill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MonthlyBill object.
        /// </summary>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        /// <param name="dateTaken">Initial value of the DateTaken property.</param>
        /// <param name="lunchAmount">Initial value of the LunchAmount property.</param>
        /// <param name="dinnerAmount">Initial value of the DinnerAmount property.</param>
        /// <param name="dailyPayment">Initial value of the DailyPayment property.</param>
        public static MonthlyBill CreateMonthlyBill(global::System.Int32 customerId, global::System.DateTime dateTaken, global::System.Int32 lunchAmount, global::System.Int32 dinnerAmount, global::System.Int32 dailyPayment)
        {
            MonthlyBill monthlyBill = new MonthlyBill();
            monthlyBill.CustomerId = customerId;
            monthlyBill.DateTaken = dateTaken;
            monthlyBill.LunchAmount = lunchAmount;
            monthlyBill.DinnerAmount = dinnerAmount;
            monthlyBill.DailyPayment = dailyPayment;
            return monthlyBill;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                if (_CustomerId != value)
                {
                    OnCustomerIdChanging(value);
                    ReportPropertyChanging("CustomerId");
                    _CustomerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerId");
                    OnCustomerIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTaken
        {
            get
            {
                return _DateTaken;
            }
            set
            {
                if (_DateTaken != value)
                {
                    OnDateTakenChanging(value);
                    ReportPropertyChanging("DateTaken");
                    _DateTaken = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateTaken");
                    OnDateTakenChanged();
                }
            }
        }
        private global::System.DateTime _DateTaken;
        partial void OnDateTakenChanging(global::System.DateTime value);
        partial void OnDateTakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LunchAmount
        {
            get
            {
                return _LunchAmount;
            }
            set
            {
                OnLunchAmountChanging(value);
                ReportPropertyChanging("LunchAmount");
                _LunchAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LunchAmount");
                OnLunchAmountChanged();
            }
        }
        private global::System.Int32 _LunchAmount;
        partial void OnLunchAmountChanging(global::System.Int32 value);
        partial void OnLunchAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DinnerAmount
        {
            get
            {
                return _DinnerAmount;
            }
            set
            {
                OnDinnerAmountChanging(value);
                ReportPropertyChanging("DinnerAmount");
                _DinnerAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DinnerAmount");
                OnDinnerAmountChanged();
            }
        }
        private global::System.Int32 _DinnerAmount;
        partial void OnDinnerAmountChanging(global::System.Int32 value);
        partial void OnDinnerAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DailyPayment
        {
            get
            {
                return _DailyPayment;
            }
            set
            {
                OnDailyPaymentChanging(value);
                ReportPropertyChanging("DailyPayment");
                _DailyPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyPayment");
                OnDailyPaymentChanged();
            }
        }
        private global::System.Int32 _DailyPayment;
        partial void OnDailyPaymentChanging(global::System.Int32 value);
        partial void OnDailyPaymentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KanakTiffinsModel", "FK_MonthlyBills_CustomerDetails", "CustomerDetails")]
        public CustomerDetail CustomerDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "CustomerDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "CustomerDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomerDetail> CustomerDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "CustomerDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomerDetail>("KanakTiffinsModel.FK_MonthlyBills_CustomerDetails", "CustomerDetails", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
